version: '3.5'
services:
  server:
    image: 'backend-challenge:src'
    build:
      context: src/
    volumes:
      - ./src:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    links:
      - api
    depends_on:
      - api
  gather:
    image: 'backend-challenge:src'
    volumes:
      - ./src:/app
      - /app/node_modules
    links:
      - api
      - db
    environment:
      - RUN_MODE=gather
    depends_on:
      - server
      - api
      - db
  db:
    image: 'mongo:3.6.20-xenial'
    volumes:
      - db-data:/data/db
      - ./db/initdb.d:/docker-entrypoint-initdb.d
  api:
    build:
      context: api/
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - '8000:8000'
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_DB=commando
    #   - POSTGRES_PASSWORD=example
volumes:
  db-data:
